name: Deploy Node.js Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.10  # Updated to a specific stable version
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/camiru/htdocs/camiru.com/
            git pull origin main
            pnpm build
            pm2 restart 0 --update-env
            # Add your application startup commands here (e.g., pm2 start your_app.js)
